### ISSUE TITLE
Trend Micro is non responsive

### ISSUE THREAD

**Issue by az0** [slolife/antivirus-false-positive-reports#3]
After trying the web form you have listed, I have been waiting waiting 53 days without a response. Did it take this long for you? I wonder if they do it FIFO, by popularity, or some other way

**Comment by slolife** [comment]
I just checked. Took about 4 business days for them to reply that they confirmed it was a false positive.

**Comment by az0** [comment]
OK, thanks for letting me know. I guess they just like you better :)
